server:
  port: 9090

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native

management:
  endpoints:
    web:
      exposure:
        include: health,refresh,info,metrics
  endpoint:
    health:
      show-details: always