spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://localhost:9090

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,refresh,info,metrics
  endpoint:
    health:
      show-details: always