spring:
    application:
        name: department-service
    config:
        import: configserver:http://${CONFIG_SERVER_URL:localhost}:9090

logging:
    level:
        org.springframework.cloud.config: DEBUG
        io.github.resilience4j.retry: DEBUG
