events {}

http {
    server {
        listen 80;

        location /employee/ {
            proxy_pass http://employee-service:8082/;
        }

        location /department/ {
            proxy_pass http://department-service:8081/;
        }
    }
}
