events {}

http {
    server {
        listen 80;

        location /employee/ {
            proxy_pass http://employee-service:8082/;
        }

        location /department/ {
            proxy_pass http://department-service:8081/;
        }
		
        location /security/ {
            proxy_pass http://security-service:9192/;
        }
		
        location /gateway/ {
            proxy_pass http://gateway-service:9191/;
        }

    }
    }
}
