server.port=8082

spring.datasource.url=jdbc:postgresql://pg-employee-ms:5432/employeemsdb
spring.datasource.username=empms
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
feign.client.name=department-service
feign.client.url=http://department-service:8081
