
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
  h2:
    console:
      enabled: true
      path: /h2-console


management:
  endpoints:
    web:
      exposure:
        include: health,refresh,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
#    ip-address: 127.0.0.1
    hostname: localhost
#    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}


resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      employee-service:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    retry-aspect-order: 2
    instances:
      employee-service:
        maxAttempts: 3
        waitDuration: 10s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
#          - feign.FeignException
          - java.lang.RuntimeException

#  ratelimiter:
#    instances:
#      employee-service:
#        limitForPeriod: 5
#        limitRefreshPeriod: 10s
#        timeoutDuration: 0
#
#  bulkhead:
#    instances:
#      employee-service:
#        maxConcurrentCalls: 5
#        maxWaitDuration: 0
#
#  timelimiter:
#    instances:
#      employee-service:
#        timeoutDuration: 3s
#        cancelRunningFuture: true
