server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employeemsdb
    username: empms
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
feign:
  client:
    name: department-service
    url : http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,refresh,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      employee-service:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    retry-aspect-order: 2
    instances:
      employee-service:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2

#  ratelimiter:
#    instances:
#      employee-service:
#        limitForPeriod: 5
#        limitRefreshPeriod: 10s
#        timeoutDuration: 0
#
#  bulkhead:
#    instances:
#      employee-service:
#        maxConcurrentCalls: 5
#        maxWaitDuration: 0
#
#  timelimiter:
#    instances:
#      employee-service:
#        timeoutDuration: 3s
#        cancelRunningFuture: true