spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: "asjkdasjkhdjashfjashfkjsahfkhasjkfhkashfklahfkjldhflksjadfhkljashflkjsdhfkjadsh2398fjsd="
  access-token-expiration: 900000
  refresh-token-expiration: 86400000
  password-reset-url: "http://${API_SERVICE:localhost}:9191/api/auth/reset-password-form?token="

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    path: /v3/api-docs
