spring.application.name=department-service
#spring.config.import=configserver:http://config-service:9090
#spring.config.import=configserver:http://localhost:9090
logging.level.org.springframework.cloud.config=DEBUG
